### ISSUE TITLE
The summary and detailed report needs to be separated. 

### ISSUE THREAD

**Issue by smdas** [sansogaam/drfa#1]
When you choose the type of output to be either summary, detailed or both, it is always creating a combined report ignoring the type chosen.

The summary and detailed reports also needs to be separated out so that the detail can be used for further analysis

**Comment by sansogaam** [comment]
Thanks and Yes its a bug and will be fixed in next release. Also simultaneously working on XLS Report generation.

**Comment by sansogaam** [comment]
Fixed the issue with the latest build its uploaded in www.drfa.in/dist/drfa-latest-bin.zip. Please download  and let me know How it works

**Comment by smdas** [comment]
Verified this for HTML output and it is working fine.
